### ISSUE TITLE
Link to Kubernetes Manifests is Dead 

### ISSUE THREAD

**Issue by M1kep** [jamf/jamfpro#10]
**Describe the bug**
At the bottom of the README there is a reference to the "JamfPro Kubernetes Manifests"(https://github.com/jamf/kubernetesManifests) but it appears that repository has been deleted.

**To Reproduce**
- Scroll to the bottom of the README.
- Click the hyperlink "JamfPro Kubernetes Manifests""
- Notice Github error

**Expected behavior**
Repository to load

**Additional context**
I assume these have been deleted rather than moved, so I'm guessing the link can be removed.

**Comment by battlecow** [comment]
Thanks for this issue as well =]
That repo was indeed removed awhile ago and failed to notice it was linked here still.  I updated the README with the link removed.  Thanks!
