### ISSUE TITLE
Release 0.0.14 not pushed to Docker Hub

### ISSUE THREAD

**Issue by schmaddi** [jamf/jamfpro#12]
The current release 0.0.14 was not pushed to Docker hub.

**Comment by battlecow** [comment]
I'll try to get that fixed up this weekend, thanks for filing an issue.

**Comment by battlecow** [comment]
Got 0.0.14 and 0.0.15 building and pushing again out to Dockerhub, please note the new location: https://hub.docker.com/r/jamf/jamfpro/tags
