### ISSUE TITLE
arm64 version?

### ISSUE THREAD

**Issue by magnusviri** [jamf/jamfpro#14]
Is it possible to put an arm64 version on Docker Hub? I run dev servers locally and just got an M1 laptop.

**Comment by battlecow** [comment]
@magnusviri  Thanks for the issue, just tagged 0.0.16 with arm64 support.  I dont have an M1 to test with, do you mind reporting back on a new issue should you find something not working?  Thanks!

**Comment by magnusviri** [comment]
Looks like it's working great, thanks!
