### ISSUE TITLE
Tomcat - /usr/local/tomcat/conf/server.xml - allow server.xml somehow to be on an external volume

### ISSUE THREAD

**Issue by omnieagle** [jamf/jamfpro#16]
**Is your feature request related to a problem? Please describe.**

Profile Service Enrollment does not send an http"S"://<server>/enroll/profile.  Since it's not a secure link it won't install the MDM profile.  You can change Tomcat Apache settings to put it behind a load balancer, but these settings do not persist.  When I pulled out /user/local/tomcat/conf and used a volume, the settings persisted but the App still does not push out an https version of the MDM profile.  Can't seem to save my own cert or a Jamf cert in the Apache Tomcat Settings either.

using Traefik for the front end load balancer and it's handling the SSL cert for the backend jamf container.

**Describe the solution you'd like**
1 - Add volume for /usr/local/tomcat/conf - may need to populate with base config.
2 - Figure out how to get https  MDM profile out to a user enrolled computer.

**Describe alternatives you've considered**
1 - figure out how to export 443 and mount a volume for the certificates for tomcat within the container

**Additional context**
At the moment this is very close to a perfect solution, but without a valid MDM to stall, it's not functional.
My email if you want more data:   steve@cs.umass.edu

Thanks for reviewing this...

**Comment by battlecow** [comment]
With version 0.0.18 this should now be possible through either manually updating the `server.template` file or mounting that filename to `/jamfpro-config`.
