### ISSUE TITLE
Please include environment variable for XFF

### ISSUE THREAD

**Issue by fauxserve** [jamf/jamfpro#21]
My ingress requires me to use a */jamfpro URL scheme, which requires me to set x-forwarded-for in the tomcat server xml file. 
In order to do this, I need to hack it with an init container.
This is not the end of the world, but it would be nice to have a supported mechanism.

P.S. - Great work on this so far. Thanks.

**Comment by battlecow** [comment]
Been a bit, just merged a PR for this: https://github.com/jamf/jamfpro/pull/23 hopefully that helps. That particular config does include the `RemoteIpValve` which should handle the x-forwarded-for header I believe.
Check out release 0.0.18
