### ISSUE TITLE
ERROR InitializeServerThread: - Error in Setup Assistant: Unhandled Case.

### ISSUE THREAD

**Issue by mks-007** [jamf/jamfpro#24]
**Describe the bug**
After doing a clean build from jamf/jamfpro:latest and using the 10.43.1 war file. I get the database schema created and the licences agreement. After agreeing I then only get a white screen and not the entire key screen. If you then remove the SetupAssistant.html it shows the agreement again.

**To Reproduce**
1. docker run -p 8880:8080 -d \
> -e DATABASE_USERNAME=user \
> -e DATABASE_PASSWORD=Password \
> -e DATABASE_HOST=mysql-8.0 \
> -v $(pwd)/10.43.1/ROOT.war:/data/ROOT.war \
> -v $(pwd)/webapps:/usr/local/tomcat/webapps \
> -v $(pwd)/logs:/usr/local/tomcat/logs \
> --network jamfpro \
> --name jamf-pro-10.43.1 \
> jamf/jamfpro:latest

**Expected behavior**
Enter licence key and create admin account

**Screenshots**
Its just a white screen

**Additional context**
The is from a clean install, I have note tried this from a backup

**Comment by battlecow** [comment]
I wasn't able to repro locally, what type of system are you using to run Docker? amd64/arm ?
Past the EULA screen are there network errors or other console errors from the browser?
Are there any jamfpro logs or catalina logs after hitting the acceptance?

**Comment by mks-007** [comment]
[JAMFSoftwareServer.zip](https://github.com/jamf/jamfpro/files/10707774/JAMFSoftwareServer.zip)

I have docker running on my QNAP with an Intel Quad Core and 16gb ram

The error above is from the catalina log

**Comment by battlecow** [comment]
There are a whole slew of sql errors in the log, I would guess because sql died somewhere after start and load. Without setting some bounds on the jamfpro server java will happily consume a systems memory. Adding some java environment variables to limit at a minimum heap with `-Xmx` would help. Setting them on the docker container should also set max memory correctly in java too without also having to set it within the container.

**Comment by battlecow** [comment]
Hey there, it's been awhile since this issue was first opened and haven't had any followup. If you can reproduce the issue please open a new issue.
