### ISSUE TITLE
Add support for configure the load balancing settings

### ISSUE THREAD

**Issue by ahousseini** [jamf/jamfpro#3]
At the moment the tomcat server is installed without any modifications to the server.xml. It would be great if following settings can be set when working behind a load balancer:

- Enable Remote IP Valve 
- Enable Proxy Port 
- Scheme
- Proxy Port

At the moment I'm manually creating the server.xml and adding it to the image like this:
`ADD server.xml /usr/local/tomcat/conf/`

**Comment by battlecow** [comment]
Modifying the server.xml is really out of scope for this project.  Either using this image as your base and doing what you are already doing, or utilizing either a Docker file mount or a Kubernetes mountPath is the recommended approach.  There are too many possible permutations in server.xml to account for all use cases.
